### ISSUE TITLE
zmq_stream producing "unaligned" np.ndarrays

### ISSUE THREAD

**Issue by cjacoby** [bmcfee/pescador#22]
A zmq_stream produces "unaligned" np.ndarrays, which theano doesn't know how to deal with. You can force a copy with np.array(), but that seems to defeat the purpose of the copy=False mode, no?

To Reproduce:
```
import pescador
import numpy as np
import theano
import theano.tensor as T

# A theano function that does something with two matrices
def theano_function():
    x = T.matrix('x')
    w = T.matrix('w')
    return theano.function([x, w], T.mean(T.dot(x, w)))

# A ZMQ Stream for testing
def data_gen():
    while True:
         yield {'X': np.random.random([8, 8])}
stream = pescador.Streamer(data_gen)
zmq_stream = pescador.zmq_stream(stream)

W = np.random.random([8, 8])
f = theano_function()

# This proves that the result is unaligned:
print (next(zmq_stream)['X'].flags.aligned)  # >>> False

# This call will fail.
f(next(zmq_stream)['X'], W)

# But this succeeds, because the copy forces the alignment
f(np.array(next(zmq_stream)['X']), W)

print (np.array(next(zmq_stream)['X']).flags.aligned)  # >>> True
```

This is the error I get:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-17de2968d2f1> in <module>()
----> 1 f(next(zmq_stream)['X'], W)

/usr/local/museami-dev/Theano-0.7.0-py2.7.egg/theano/compile/function_module.pyc in __call__(self, *args, **kwargs)
    511                     try:
    512                         s.storage[0] = s.type.filter(arg, strict=s.strict,
--> 513                                 allow_downcast=s.allow_downcast)
    514 
    515                     except Exception, e:

/usr/local/museami-dev/Theano-0.7.0-py2.7.egg/theano/tensor/type.pyc in filter(self, data, strict, allow_downcast)
    178                             "object shape", data.shape,
    179                             "object strides", data.strides,
--> 180                             "object dtype", data.dtype)
    181 
    182         i = 0

TypeError: ('Bad input argument to theano function with name "<ipython-input-2-96a0c586bb31>:5"  at index 0(0-based)', 'The numpy.ndarray object is not aligned. Theano C code does not support that.', 'object buffer\xb01\x1fHR\x90\xae?\x80446LG\xbd?\x04h "\x87\xfb\xce?\
.... [a bunch of crap here] ..... x1b\xcc\xed?', 'object shape', (8, 8), 'object strides', (64, 8), 'object dtype', dtype('float64'))
```

**Comment by ejhumphrey** [comment]
so there's a chance this might be unavoidable, and might be the bit Brian mentioned about figuring out whether or not the buffer sharing actually works. The first (and maybe only) instance I found of this in pescador tests corresponds to an `np.allclose` call, which might be doing a copy / array call anyways.

https://github.com/bmcfee/pescador/blob/master/tests/test_streams.py#L17

now, that said, even if copying _some_ data is necessary, I would expect that time cost to be significantly  less than reading from disk / slicing / all that other jazz. 

thoughts?

**Comment by bmcfee** [comment]
That's strange, and not something I ever thought to test with.

That said, I've used it with tensorflow and it works fine. Will look into this more later.

**Comment by bmcfee** [comment]
Can you print out the whole .flags for the received array?

**Comment by cjacoby** [comment]
Here's an example one:
```sampler: <generator object zmq_stream at 0x10dae30a0>
Flags:  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : False
  ALIGNED : False
  UPDATEIFCOPY : False```

**Comment by bmcfee** [comment]
When using the zmq_streamer, can you print flags from the worker side as well?

According to [the docs](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.ndarray.flags.html), it may be a simple matter of re-setting the aligned flag on the consumer side, provided that it actually is aligned on the worker side.  That would be a pretty easy fix.

If that doesn't work... I'm not sure what to do about it.

**Comment by bmcfee** [comment]
@cjacoby can you pull branch #23 and let me know if it fixes the problem for you?

**Comment by cjacoby** [comment]
I get a different sort of error now when I call next on the `zmq_stream`. (I ... think ... I'm doing this right? I used the same code as above.)

```
In [21]: next(zmq_stream)['X']
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-21-128133f32e70> in <module>()
----> 1 next(zmq_stream)['X']

/Users/cjacoby/Documents/devel/pescador/pescador/zmq_stream.py in zmq_stream(streamer, max_batches, min_port, max_port, max_tries, copy, timeout)
    159
    160     except:
--> 161         six.reraise(*sys.exc_info())
    162
    163     finally:

/Users/cjacoby/Documents/devel/pescador/pescador/zmq_stream.py in zmq_stream(streamer, max_batches, min_port, max_port, max_tries, copy, timeout)
    153         # Yield from the queue as long as it's open
    154         while worker.is_alive():
--> 155             yield zmq_recv_batch(socket)
    156
    157     except StopIteration:

/Users/cjacoby/Documents/devel/pescador/pescador/zmq_stream.py in zmq_recv_batch(socket, flags, copy, track)
     70                                                dtype=header['dtype'])
     71         results[header['key']].shape = header['shape']
---> 72         results[header['key']].flags['ALIGNED'] = header['aligned']
     73
     74     return results

ValueError: cannot set aligned flag of mis-aligned array to True
```

**Comment by bmcfee** [comment]
OK, that's interesting.  What version of Python and pyzmq do you have?

**Comment by cjacoby** [comment]
Python=2.7.10
pyzmq=14.7.0

**Comment by bmcfee** [comment]
Ok.  This ( #23 ) works on Travis with pyzmq 15.2 and python 3, but not on python 2.  I suspect this might be down to the fact that python 3 uses `memoryview` instead of `buffer`.  It should be possible to use memoryview in both, but my first cut at this didn't work because numpy wouldn't reinterpret the memoryview as an ndarray correctly.

Perhaps it's worth another shot.

**Comment by cjacoby** [comment]
I've decided to switch to python3 for now anyway, so no rush?

**Comment by bmcfee** [comment]
Ok.  I'd still like to solve it, but it can wait.

**Comment by cjacoby** [comment]
Agreed

**Comment by lixiangnlp** [comment]
@bmcfee I also encounter the problem. Do you have any way to solve it when using Python 2.7? Thanks.

**Comment by bmcfee** [comment]
@lixiangnlp I reported the issue on pyzmq [here](https://github.com/zeromq/pyzmq/issues/864), but afaik nobody's touched it yet.  My best advice at this point is to not use py27.
