### ISSUE TITLE
Desired behavior for a BufferedStreamer

### ISSUE THREAD

**Issue by cjacoby** [bmcfee/pescador#33]
## Question 1: Should `batch_size` be guaranteed?
If you have a `BufferedStreamer` with a batch_size, is it necessary to guarantee that the batch returned is always of that size?

(Or: Both of these possibilities are desirable and should be controlled from a parameter in the constructor)

## Question 2: What should the `max_batches` parameter of the `BufferedStreamer.generate()`  do?
(or more abstractly, any child class of Streamer)
*`BufferedStreamers` are intended to consume a `Streamer` class (with a `generate()` function), and produce batches of `max_batches` length.*

Should it:

(a) Pass the `max_batches` parameter through to the wrapped `generate`, such that the max individual "samples" generated is `max_batches`?

(b) Generate `max_batches` buffered batches, such that there are up to `max_batches` based on the number of samples available, generated from *this* Streamer, but an individual batch will not necessarily contain `batch_size` samples, if the consumed `Streamer` runs out of samples (ie throws StopIteration).

(c) Both of these behaviors are desirable and should be toggled from a parameter in the constructor.

My personal feeling on this is that (b) is what actually makes sense, and that if you want to set the max samples, you would do it in the construction of the first streamer / the slicer, and that `max_batches` should always make sense in regards to the current context. But... I could see an argument for the other way, so I though I would check first.

## Examples
```python
def some_generator(n_samples=9):
    for x in range(n_samples):
          yield {'x': x}

stream1 = Streamer(some_generator)
batch_stream = BufferedStreamer(stream1, batch_size=2)
for i, batch in enumerate(batch_stream.generate(max_batches=5):
     print(x, batch)
```

Under (a), incomplete batches allowed (approx output):
```python
0 {'x': [0, 1]}
1 {'x': [2, 3]}
2 {'x': [4]}
# raise StopIteration(), etc.
```

Under (b), incomplete batches allowed (approx output):
```python
0 {'x': [0, 1]}
1 {'x': [2, 3]}
2 {'x': [4, 5]}
3 {'x': [6, 7]}
4 {'x': [8]}
# raise StopIteration(), etc.
```

Under (b), incomplete batches not allowed (approx output):
```python
0 {'x': [0, 1]}
1 {'x': [2, 3]}
2 {'x': [4, 5]}
3 {'x': [6, 7]}
# raise StopIteration(), etc.
```

**Comment by bmcfee** [comment]
> If you have a BufferedStreamer with a batch_size, is it necessary to guarantee that the batch returned is always of that size?
> 
> (Or: Both of these possibilities are desirable and should be controlled from a parameter in the constructor)

I think this should be a flag.





> Question 2: What should the max_batches parameter of the BufferedStreamer.generate() do?

`max_batches` is just a limiter on the length of the stream.  You could do this equally well by izipping against `range(max_batches)`.

It's not clear that we need this option in the streamer object; it is necessary in the mux, but like I said, it can be accomplished by izip.

What do you think?
