### ISSUE TITLE
Decorrelating generators with Poisson-sampled limits.

### ISSUE THREAD

**Issue by ejhumphrey** [bmcfee/pescador#4]
It seems undesirable that generators created with ```max_samples```, drawn from the same Poisson distribution, all die approximately around the same time. If the module is used to lazily load data, you'll end up with disk read spikes as a function of the lambda parameter. Over time, it'll work itself out, but ... this can be a *long* time, and will vary with lambda.

An alternative: draw both ```max_samples``` and, for the initial population only, the value of the counter (as opposed to just zero). Uniformly distributing the counter values should stagger the birth / death of generators and more evenly distribute disk reading in time.

**Comment by bmcfee** [comment]
Closing this, since multiplexing over zmq streams should make this effect disappear.
